FROM node:24-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_LOGIPAYROLL_API_URL=http://localhost:3733/api/v1
ENV NEXT_PUBLIC_LOGIPAYROLL_API_URL=$NEXT_PUBLIC_LOGIPAYROLL_API_URL
COPY . .
RUN npm install -g pnpm && pnpm install -g pnpm && pnpm install --frozen-lockfile
RUN pnpm run build -w logipayroll-web

FROM node:24-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_LOGIPAYROLL_API_URL=http://localhost:3733/api/v1
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/apps/logipayroll-web ./apps/logipayroll-web
COPY --from=builder /app/packages ./packages
RUN addgroup -S logipayroll && adduser -S logipayroll -G logipayroll \
  && chown -R logipayroll:logipayroll /app
USER logipayroll
WORKDIR /app/apps/logipayroll-web
EXPOSE 3600
CMD ["npm", "run", "start"]
