FROM node:24-alpine AS builder
WORKDIR /app
ARG WORKSPACE
COPY . .
RUN npm ci
RUN npm run build -w ${WORKSPACE}

FROM node:24-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ARG WORKSPACE
ENV WORKSPACE=${WORKSPACE}
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/apps/${WORKSPACE} ./apps/${WORKSPACE}
COPY --from=builder /app/packages ./packages
RUN addgroup -S worker && adduser -S worker -G worker \
  && chown -R worker:worker /app
USER worker
CMD ["sh", "-c", "node apps/${WORKSPACE}/dist/apps/${WORKSPACE}/src/main.js"]
