FROM node:24-alpine AS builder
WORKDIR /app
ARG WORKSPACE
COPY . .
RUN npm install -g pnpm && pnpm install -g pnpm && pnpm install --frozen-lockfile
RUN pnpm run build -w ${WORKSPACE}

FROM node:24-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ARG WORKSPACE
ENV WORKSPACE=${WORKSPACE}
RUN addgroup -S worker && adduser -S worker -G worker
COPY --chown=worker:worker --from=builder /app/node_modules ./node_modules
COPY --chown=worker:worker --from=builder /app/package*.json ./
COPY --chown=worker:worker --from=builder /app/apps/${WORKSPACE} ./apps/${WORKSPACE}
COPY --chown=worker:worker --from=builder /app/packages ./packages
USER worker
CMD ["sh", "-c", "node apps/${WORKSPACE}/dist/apps/${WORKSPACE}/src/main.js"]
